version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Build started on `date`
      - echo No build needed for HTML

artifacts:
  files:
    - '**/*'
